# -*- coding: utf-8 -*-
"""PyInstaller 构建脚本 + loop_hermes.spec 生成。

将 loop-hermes 打包为独立可执行文件（Linux/macOS/Windows）。

功能:
    1. 自动生成 loop_hermes.spec 文件（PyInstaller 配置）
    2. 跨平台构建（检测当前 OS 并应用对应配置）
    3. 版本注入（从 loop_hermes.__version__ 读取）
    4. 依赖分析（bundled packages 列表）
    5. 一键构建命令

使用方式:
    python build.py              # 为当前平台构建
    python build.py --spec-only  # 仅生成 .spec 文件
    python build.py --clean      # 清理 dist/build 目录后构建
    python build.py --onefile    # 单文件模式
    python build.py --onedir     # 单目录模式（默认）

生成的 spec 文件:
    loop_hermes.spec —— PyInstaller spec 文件

输出:
    dist/loop-hermes (Linux/macOS) 或 dist/loop-hermes.exe (Windows)
"""

import os
import sys
import shutil
import logging
import argparse
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any

logger = logging.getLogger("loop_hermes.build")

# ============================================================================
# 构建配置常量
# ============================================================================

# 应用名称
APP_NAME = "loop-hermes"

# 入口点
ENTRY_SCRIPT = "loop_hermes/cli.py"
ENTRY_FUNCTION = "main"

# 版本
try:
    from . import __version__ as APP_VERSION
except ImportError:
    APP_VERSION = "0.1.0"

# 需要打包的 Python 包
BUNDLED_PACKAGES = [
    "loop_hermes",
    "jsonschema",
    "jsonschema_specifications",
    "referencing",
    "rpds",
]

# 需要包含的数据文件
DATA_FILES = [
    ("loop_hermes/prompts/*.txt", "loop_hermes/prompts"),
]

# 隐藏导入（PyInstaller 可能遗漏的依赖）
HIDDEN_IMPORTS = [
    "jsonschema",
    "jsonschema.validators",
    "jsonschema.exceptions",
    "json",
    "logging",
    "pathlib",
    "hashlib",
    "uuid",
    "copy",
    "shutil",
    "datetime",
    "re",
    "select",
    "subprocess",
]

# 排除的包（减小体积）
EXCLUDED_MODULES = [
    "tkinter",
    "matplotlib",
    "scipy",
    "numpy",
    "pandas",
    "PIL",
    "cv2",
    "tensorflow",
    "torch",
]

# 平台特定配置
PLATFORM_CONFIG = {
    "linux": {
        "target_name": "loop-hermes",
        "strip": True,
        "upx": True,
    },
    "macos": {
        "target_name": "loop-hermes",
        "strip": True,
        "upx": True,
        "bundle_identifier": "com.loop-hermes.app",
    },
    "windows": {
        "target_name": "loop-hermes.exe",
        "strip": False,
        "upx": False,
        "console": True,
    },
}


# ============================================================================
# SPEC 文件生成
# ============================================================================


def generate_spec(
    output_path: str = "loop_hermes.spec",
    onefile: bool = False,
) -> str:
    """生成 PyInstaller .spec 文件。

    Args:
        output_path: spec 文件输出路径
        onefile: True=单文件模式，False=单目录模式

    Returns:
        spec 文件路径
    """
    spec_content = _generate_spec_content(onefile)
    Path(output_path).write_text(spec_content, encoding="utf-8")
    logger.info("已生成 spec 文件: %s", output_path)
    return output_path


def _generate_spec_content(onefile: bool = False) -> str:
    """生成 spec 文件内容。

    Args:
        onefile: 单文件模式

    Returns:
        spec 文件文本内容
    """
    project_root = str(Path(__file__).parent.parent)

    # 收集数据文件
    datas_lines = ""
    prompts_dir = Path(project_root) / "loop_hermes" / "prompts"
    if prompts_dir.exists():
        for f in prompts_dir.glob("*.txt"):
            datas_lines += f"        ('{f}', 'loop_hermes/prompts'),\n"

    datas_lines = datas_lines.rstrip(",\n")

    # 隐藏导入
    hidden_imports_lines = ",\n".join(
        f"        '{h}'" for h in HIDDEN_IMPORTS
    )

    # 排除模块
    excluded_lines = ",\n".join(
        f"        '{e}'" for e in EXCLUDED_MODULES
    )

    spec = f'''# -*- coding: utf-8 -*-
# loop-hermes PyInstaller spec file
# Auto-generated by loop_hermes/build.py
# Generated at: {datetime.now(timezone.utc).isoformat()}
# Version: {APP_VERSION}

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['{ENTRY_SCRIPT}'],
    pathex=['{project_root}'],
    binaries=[],
    datas=[
{datas_lines}
    ],
    hiddenimports=[
{hidden_imports_lines}
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[
{excluded_lines}
    ],
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher,
)
'''

    if onefile:
        spec += f'''
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='{APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
'''
    else:
        spec += f'''
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='{APP_NAME}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='{APP_NAME}',
)
'''

    return spec


# ============================================================================
# 构建流程
# ============================================================================


def detect_platform() -> str:
    """检测当前构建平台。

    Returns:
        "linux" / "macos" / "windows"
    """
    if sys.platform.startswith("linux"):
        return "linux"
    if sys.platform == "darwin":
        return "macos"
    if sys.platform in ("win32", "cygwin"):
        return "windows"
    return "unknown"


def clean_build() -> None:
    """清理构建产物目录（dist/ + build/）。"""
    project_root = Path(__file__).parent.parent
    for d in ("dist", "build"):
        path = project_root / d
        if path.exists():
            shutil.rmtree(str(path))
            logger.info("已清理: %s", path)

    # 清理 .spec 缓存
    spec_cache = project_root / "loop_hermes.spec"
    if spec_cache.exists():
        spec_cache.unlink()
        logger.info("已清理: %s", spec_cache)


def run_pyinstaller(spec_path: str) -> int:
    """运行 PyInstaller 构建。

    Args:
        spec_path: spec 文件路径

    Returns:
        PyInstaller 退出码
    """
    import subprocess

    cmd = [sys.executable, "-m", "PyInstaller", "--clean", spec_path]
    logger.info("执行: %s", " ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=str(Path(spec_path).parent),
    )
    return result.returncode


def verify_build(onefile: bool = False) -> Dict[str, Any]:
    """验证构建产物。

    检查可执行文件是否存在、文件大小、基本运行测试。

    Args:
        onefile: 是否为单文件模式

    Returns:
        {"success": bool, "executable_path": str, "size_mb": float, "errors": [str]}
    """
    platform = detect_platform()
    config = PLATFORM_CONFIG.get(platform, PLATFORM_CONFIG["linux"])
    project_root = Path(__file__).parent.parent

    if onefile:
        exe_path = project_root / "dist" / config["target_name"]
    else:
        exe_path = project_root / "dist" / APP_NAME / config["target_name"]

    errors = []

    if not exe_path.exists():
        errors.append(f"可执行文件不存在: {exe_path}")
        return {
            "success": False,
            "executable_path": str(exe_path),
            "size_mb": 0,
            "errors": errors,
        }

    size_mb = exe_path.stat().st_size / (1024 * 1024)

    # 基本运行测试（--help）
    try:
        import subprocess
        result = subprocess.run(
            [str(exe_path), "--help"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode != 0:
            errors.append(f"--help 测试失败: {result.stderr[:200]}")
    except Exception as e:
        errors.append(f"运行测试失败: {e}")

    return {
        "success": len(errors) == 0,
        "executable_path": str(exe_path),
        "size_mb": round(size_mb, 2),
        "errors": errors,
    }


# ============================================================================
# CLI 入口
# ============================================================================


def build_parser() -> argparse.ArgumentParser:
    """构建 CLI 参数解析器。"""
    parser = argparse.ArgumentParser(
        prog="python build.py",
        description="loop-hermes PyInstaller 构建脚本",
    )
    parser.add_argument(
        "--spec-only", action="store_true",
        help="仅生成 .spec 文件，不执行构建",
    )
    parser.add_argument(
        "--clean", action="store_true",
        help="清理 dist/build 目录后再构建",
    )
    parser.add_argument(
        "--onefile", action="store_true",
        help="单文件模式（合并为一个可执行文件）",
    )
    parser.add_argument(
        "--onedir", action="store_true", default=True,
        help="单目录模式（默认）",
    )
    parser.add_argument(
        "--output", type=str, default="loop_hermes.spec",
        help="spec 文件输出路径",
    )
    parser.add_argument(
        "--no-verify", action="store_true",
        help="构建后不验证产物",
    )
    return parser


def main(argv: Optional[List[str]] = None) -> int:
    """构建脚本入口。

    Args:
        argv: 命令行参数

    Returns:
        退出码
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    parser = build_parser()
    args = parser.parse_args(argv)

    project_root = str(Path(__file__).parent.parent)
    os.chdir(project_root)

    # 清理
    if args.clean:
        clean_build()

    # 生成 spec
    spec_path = generate_spec(
        output_path=args.output,
        onefile=args.onefile,
    )

    if args.spec_only:
        logger.info("仅生成 spec 文件，跳过构建")
        return 0

    # 运行 PyInstaller
    logger.info("开始 PyInstaller 构建...")
    ret = run_pyinstaller(spec_path)

    if ret != 0:
        logger.error("PyInstaller 构建失败（退出码 %d）", ret)
        return ret

    # 验证
    if not args.no_verify:
        result = verify_build(args.onefile)
        if result["success"]:
            logger.info(
                "构建成功: %s (%.2f MB)",
                result["executable_path"], result["size_mb"],
            )
        else:
            logger.error("构建验证失败: %s", result["errors"])
            return 1

    logger.info("构建完成")
    return 0


if __name__ == "__main__":
    sys.exit(main())
